const PHONETICS = {
  "impress": "/ɪmˈpres/",
  "exchange": "/ɪksˈtʃeɪndʒ/",
  "guy": "/gaɪ/",
  "lecture": "/ˈlektʃə(r)/",
  "concentrate": "/ˈkɒnsntreɪt/",
  "registration": "/ˌredʒɪˈstreɪʃn/",
  "experiment": "/ɪkˈsperɪmənt/",
  "register": "/ˈredʒɪstə(r)/",
  "awkward": "/ˈɔːkwəd/",
  "sex": "/seks/",
  "junior": "/ˈdʒuːnɪə(r)/",
  "female": "/ˈfiːmeɪl/",
  "male": "/meɪl/",
  "explore": "/ɪkˈsplɔː(r)/",
  "nationality": "/ˌnæʃəˈnæləti/",
  "confident": "/ˈkɒnfɪdənt/",
  "nation": "/ˈneɪʃn/",
  "confidence": "/ˈkɒnfɪdəns/",
  "designer": "/dɪˈzaɪnə(r)/",
  "forward": "/ˈfɔːwəd/",
  "design": "/dɪˈzaɪn/",
  "campus": "/ˈkæmpəs/",
  "formal": "/ˈfɔːml/",
  "anxious": "/ˈæŋkʃəs/",
  "flash": "/flæʃ/",
  "annoyed": "/əˈnɔɪd/",
  "annoy": "/əˈnɔɪ/",
  "frightened": "/ˈfraɪtnd/",
  "p.m.": "/ˌpiːˈem/",
  "organise": "/ˈɔːgənaɪz/",
  "a.m.": "/ˌeɪˈem/",
  "senior": "/ˈsiːnɪə(r)/",
  "goal": "/gəʊl/",
  "strategy": "/ˈstrætədʒi/",
  "outgoing": "/ˈaʊtgəʊɪŋ/",
  "partner": "/ˈpɑːtnə(r)/",
  "impression": "/ɪmˈpreʃn/",
  "improve": "/ɪmˈpruːv/",
  "curious": "/ˈkjʊəriəs/",
  "extra-curricular": "/ˌekstrəkəˈrɪkjʊlə/",
  "company": "/ˈkʌmpəni/",
  "personality": "/ˌpɜːsəˈnæləti/",
  "extra": "/ˈekstrə/",
  "style": "/staɪl/",
  "obviously": "/ˈɒbviəsli/",
  "revise": "/rɪˈvaɪz/",
  "quit": "/kwɪt/",
  "responsible": "/rɪˈspɒnsəbl/",
  "responsibility": "/rɪˌspɒnsəˈbɪləti/",
  "teenage": "/ˈtiːneɪdʒ/",
  "solution": "/səˈluːʃn/",
  "teenager": "/ˈtiːneɪdʒə(r)/",
  "schedule": "/ˈʃedjuːl;ˈskedʒuːl/",
  "ballet": "/ˈbæleɪ;bæˈleɪ/",
  "volunteer": "/ˌvɒlənˈtɪə(r)/",
  "debate": "/dɪˈbeɪt/",
  "plate": "/pleɪt/",
  "adventure": "/ədˈventʃə(r)/",
  "prefer": "/prɪˈfɜː(r)/",
  "youth": "/juːθ/",
  "survival": "/səˈvaɪvl/",
  "content": "/ˈkɒntent/",
  "expert": "/ˈekspɜːt/",
  "movement": "/ˈmuːvmənt/",
  "behaviour": "/bɪˈheɪvjə(r)/",
  "greenhouse": "/ˈgriːnhaʊs/",
  "generation": "/ˌdʒenəˈreɪʃn/",
  "attract": "/əˈtrækt/",
  "suitable": "/ˈsuːtəbl/",
  "focus": "/ˈfəʊkəs/",
  "actually": "/ˈæktʃʊəli/",
  "challenge": "/ˈtʃælɪndʒ/",
  "title": "/ˈtaɪtl/",
  "addicted": "/əˈdɪktɪd/",
  "addict": "/ˈædɪkt/",
  "topic": "/ˈtɒpɪk/",
  "freshman": "/ˈfreʃmən/",
  "adult": "/ˈædʌlt/",
  "confusing": "/kənˈfjuːzɪŋ/",
  "confuse": "/kənˈfjuːz/",
  "chicago": "/ʃɪˈkɑːgəʊ/",
  "confused": "/kənˈfjuːzd/",
  "seoul": "/səʊl/",
  "fluent": "/ˈfluːənt/",
  "graduate": "/ˈgrædʒueɪt/",
  "recommend": "/ˌrekəˈmend/",
  "castle": "/ˈkɑːsl/",
  "apply": "/əˈplaɪ/",
  "advanced": "/ədˈvɑːnst/",
  "advance": "/ədˈvɑːns/",
  "visa": "/ˈviːzə/",
  "rent": "/rent/",
  "literature": "/ˈlɪtrətʃə(r)/",
  "pack": "/pæk/",
  "soldier": "/ˈsəʊldʒə(r)/",
  "transport": "/ˈtrænspɔːt/",
  "amazing": "/əˈmeɪzɪŋ/",
  "hike": "/haɪk/",
  "amazed": "/əˈmeɪzd/",
  "arrangement": "/əˈreɪndʒmənt/",
  "extremely": "/ɪkˈstriːmli/",
  "economy": "/ɪˈkɒnəmi/",
  "source": "/sɔːs/",
  "economic": "/ˌiːkəˈnɒmɪk/",
  "narrow": "/ˈnærəʊ/",
  "credit": "/ˈkredɪt/",
  "flat": "/flæt/",
  "detail": "/ˈdiːteɪl/",
  "powerful": "/ˈpaʊəfl/",
  "empire": "/ˈempaɪə(r)/",
  "request": "/rɪˈkwest/",
  "emperor": "/ˈempərə(r)/",
  "site": "/saɪt/",
  "view": "/vjuː/",
  "sight": "/saɪt/",
  "official": "/əˈfɪʃl/",
  "statue": "/ˈstætʃuː/",
  "bce": "/ˌbiːsiːˈiː/",
  "recognise": "/ˈrekəgnaɪz/",
  "tomb": "/tuːm/",
  "unearth": "/ʌnˈɜːθ/",
  "type": "/taɪp/",
  "comment": "/ˈkɒment/",
  "accommodation": "/əˌkɒməˈdeɪʃn/",
  "the eiffel tower": "/ˌaɪflˈtaʊə(r)/",
  "neuschwanstein castle": "/nɔɪˈʃvɑːnʃtaɪn/",
  "unique": "/juˈniːk/",
  "path": "/pɑːθ/",
  "iceland": "/ˈaɪslənd/",
  "disneyland": "/ˈdɪznilænd/",
  "destination": "/ˌdestɪˈneɪʃn/",
  "peru": "/pəˈruː/",
  "the andes mountains": "/ˈændiːz/",
  "admire": "/ədˈmaɪə(r)/",
  "architecture": "/ˈɑːkɪtektʃə(r)/",
  "the inca empire": "/ˈɪŋkə/",
  "machu picchu": "/ˌmɑːtʃuːˈpiːktʃuː/",
  "architect": "/ˈɑːkɪtekt/",
  "spain": "/speɪn/",
  "brochure": "/ˈbrəʊʃə(r);broʊˈʃur/",
  "spanish": "/ˈspænɪʃ/",
  "package": "/ˈpækɪdʒ/",
  "cusco": "/ˈkʊskəʊ/",
  "lake titicaca": "/ˌtɪtɪˈkɑːkɑː/",
  "the uros": "/ˈjuːrəʊz/",
  "contact": "/ˈkɒntækt/",
  "the terracotta army": "/ˌterəˈkɒtə/",
  "civilisation": "/ˌsɪvəlaɪˈzeɪʃn/",
  "fitness": "/ˈfɪtnəs/",
  "soccer": "/ˈsɒkə(r)/",
  "compete": "/kəmˈpiːt/",
  "stadium stadiums stadia": "/ˈsteɪdiəm/",
  "pretend": "/prɪˈtend/",
  "boxing": "/ˈbɒksɪŋ/",
  "badminton": "/ˈbædmɪntən/",
  "million": "/ˈmɪljən/",
  "marathon": "/ˈmærəθən/",
  "cheat": "/tʃiːt/",
  "event": "/ɪˈvent/",
  "ski": "/skiː/",
  "audience": "/ˈɔːdiəns/",
  "positive": "/ˈpɒzətɪv/",
  "host": "/həʊst/",
  "slim": "/slɪm/",
  "track": "/træk/",
  "diet": "/ˈdaɪət/",
  "gym": "/dʒɪm/",
  "rather": "/ˈrɑːðə(r)/",
  "gymnastics": "/dʒɪmˈnæstɪks/",
  "push-up": "/ˈpʊʃʌp/",
  "sweat": "/swet/",
  "jog": "/dʒɒg/",
  "legend": "/ˈledʒənd/",
  "stress": "/stres/",
  "athlete": "/ˈæθliːt/",
  "master": "/ˈmɑːstə(r)/",
  "error": "/ˈerə(r)/",
  "honour": "/ˈɒnə(r)/",
  "glory": "/ˈglɔːri/",
  "medal": "/ˈmedl/",
  "disaster": "/dɪˈzɑːstə(r)/",
  "championship": "/ˈtʃæmpiənʃɪp/",
  "tornado -oes -os": "/tɔːˈneɪdəʊ/",
  "drought": "/draʊt/",
  "champion": "/ˈtʃæmpiən/",
  "landslide": "/ˈlændslaɪd/",
  "determination": "/dɪˌtɜːmɪˈneɪʃn/",
  "apart": "/əˈpɑːt/",
  "slide": "/slaɪd/",
  "tsunami": "/tsuːˈnɑːmi/",
  "injure": "/ˈɪndʒə(r)/",
  "flood": "/flʌd/",
  "injured": "/ˈɪndʒəd/",
  "injury": "/ˈɪndʒəri/",
  "captain": "/ˈkæptɪn/",
  "volcanic eruption": "/vɒlˈkænɪkɪˈrʌpʃn/",
  "graceful": "/ˈgreɪsfl/",
  "magnitude": "/ˈmægnɪtjuːd/",
  "strength": "/streŋθ/",
  "rescue": "/ˈreskjuː/",
  "damage": "/ˈdæmɪdʒ/",
  "failure": "/ˈfeɪljə(r)/",
  "destroy": "/dɪˈstrɔɪ/",
  "power": "/ˈpaʊə(r)/",
  "evacuate": "/ɪˈvækjueɪt/",
  "tap": "/tæp/",
  "helicopter": "/ˈhelɪkɒptə(r)/",
  "pipe": "/paɪp/",
  "death": "/deθ/",
  "whistle": "/ˈwɪsl/",
  "affect": "/əˈfekt/",
  "shelter": "/ˈʃeltə(r)/",
  "emergency": "/iˈmɜːdʒənsi/",
  "calm": "/kɑːm/",
  "crack": "/kræk/",
  "aid": "/eɪd/",
  "gas": "/gæs/",
  "kit": "/kɪt/",
  "ruin": "/ˈruːɪn/",
  "percent)": "/ˈruːɪn/",
  "crash": "/kræʃ/",
  "brick": "/brɪk/",
  "sweep": "/swiːp/",
  "metal": "/ˈmetl/",
  "shock": "/ʃɒk/",
  "wave": "/weɪv/",
  "strike": "/straɪk/",
  "electricity": "/ɪˌlekˈtrɪsəti/",
  "trap": "/træp/",
  "deliver": "/dɪˈlɪvə(r)/",
  "bury": "/ˈberi/",
  "breathe": "/briːð/",
  "summary": "/ˈsʌməri/",
  "revive": "/rɪˈvaɪv/",
  "effect": "/ɪˈfekt/",
  "revival": "/rɪˈvaɪvl/",
  "length": "/leŋθ/",
  "effort": "/ˈefət/",
  "unify": "/ˈjuːnɪfaɪ/",
  "ecuador": "/ˈekwədɔː(r)/",
  "wisdom": "/ˈwɪzdəm/",
  "memphis": "/ˈmemfis/",
  "context": "/ˈkɒntekst/",
  "alberta": "/ælˈbɜːtə/",
  "suffer": "/ˈsʌfə/",
  "colombo": "/kəˈlʌmbəʊ/",
  "sri lanka": "/ˌsrɪˈlæŋkə/",
  "volcano -oes -os": "/vɒlˈkeɪnəʊ/",
  "indonesia": "/ˌɪndəˈniːʒə/",
  "erupt": "/ɪˈrʌpt/",
  "thailand": "/ˈtaɪlænd/",
  "malaysia": "/məˈleɪʒə/",
  "supply": "/səˈplaɪ/",
  "sumatra island": "/sʊˈmɑːtrə/",
  "typhoon": "/taɪˈfuːn/",
  "chandra theeravit": "/ˈtʃɑːndrəˈθiːrəvit/",
  "hurricane": "/ˈhʌrɪkən/",
  "survive": "/səˈvaɪv/",
  "calligraphy": "/kəˈlɪgrəfi/",
  "global": "/ˈgləʊbl/",
  "billion": "/ˈbɪljən/",
  "affair": "/əˈfeə(r)/",
  "native": "/ˈneɪtɪv/",
  "appreciate": "/əˈpriːʃieɪt/",
  "specific": "/spəˈsɪfɪk/",
  "ce": "/ˌsiːˈiː/",
  "struggle": "/ˈstrʌgl/",
  "refer": "/rɪˈfɜː(r)/",
  "tongue": "/tʌŋ/",
  "system": "/ˈsɪstəm/",
  "petrol gas": "/ˈpetrəl/",
  "despite": "/dɪˈspaɪt/",
  "subway underground": "/ˈsʌbweɪ/",
  "apartment": "/əˈpɑːtmənt/",
  "factor": "/ˈfæktə(r)/",
  "based": "/beɪst/",
  "pants": "/pænts/",
  "base": "/beɪs/",
  "beg": "/beg/",
  "equal": "/ˈiːkwəl/",
  "bone": "/bəʊn/",
  "gap": "/gæp/",
  "shell": "/ʃel/",
  "demand": "/dɪˈmɑːnd/",
  "symbol": "/ˈsɪmbl/",
  "carve": "/kɑːv/",
  "dynasty": "/ˈdɪnəsti;ˈdaɪ-/",
  "vocabulary": "/vəˈkæbjələri;-leri/",
  "variety": "/vəˈraɪəti/",
  "description": "/dɪˈskrɪpʃn/",
  "relate": "/rɪˈleɪt/",
  "major": "/ˈmeɪdʒə(r)/",
  "korean": "/kəˈriːən/",
  "dialect": "/ˈdaɪəlekt/",
  "danish": "/ˈdeɪnɪʃ/",
  "means": "/miːnz/",
  "classic": "/ˈklæsɪk/",
  "denmark": "/ˈdenmɑːk/",
  "regard": "/rɪˈgɑːd/",
  "character": "/ˈkærəktə(r)/"
};
