const PHONETICS = {
  "heritage": "/ˈhɛrətədʒ/",
  "creatively": "/kriˈeɪtɪvli/",
  "creative": "/kriˈeɪtɪv/",
  "temple": "/ˈtɛmpəl/",
  "relic": "/ˈrɛlɪk/",
  "mount": "/ˈmaʊnt/",
  "former": "/ˈfɔrmɚ/",
  "clue": "/ˈklu/",
  "preserve": "/prəˈzɝv/",
  "promote": "/prəˈmoʊt/",
  "cypress": "/ˈsaɪprəs/",
  "app": "/ˈæp/",
  "application": "/ˌæpləˈkeɪʃən/",
  "take part in": "/ˈteɪk ˈpɑrt ɪn/",
  "give way to": "/ˈɡɪv ˈweɪ ˈtu/",
  "balance": "/ˈbæləns/",
  "keep balance": "/ˈkip ˈbæləns/",
  "lead to": "/ˈlɛd ˈtu/",
  "dam": "/ˈdæm/",
  "proposal": "/prəˈpoʊzəl/",
  "make a proposal": "/ˈmeɪk ə prəˈpoʊzəl/",
  "protest": "/ˈproʊˌtɛst/",
  "likely": "/ˈlaɪkli/",
  "turn to": "/ˈtɝn ˈtu/",
  "committee": "/kəˈmɪti/",
  "establish": "/ɪˈstæblɪʃ/",
  "limit": "/ˈlɪmət/",
  "prevent": "/prɪˈvɛnt/",
  "prevent ... from ...": "/prɪˈvɛnt ˈfrʌm/",
  "loss": "/ˈlɔs/",
  "contribution": "/ˌkɑntrəˈbjuʃən/",
  "contribute": "/kəˈntrɪbjut/",
  "department": "/dɪˈpɑrtmənt/",
  "fund": "/ˈfʌnd/",
  "within": "/wɪˈðɪn/",
  "investigate": "/ˌɪˈnvɛstəˌɡeɪt/",
  "issue": "/ˈɪʃu/",
  "conduct": "/ˈkɑndəkt/",
  "document": "/ˈdɑkjəmɛnt/",
  "donate": "/ˈdoʊˌneɪt/",
  "donate ... to ...": "/ˈdoʊˌneɪt ˈtu/",
  "disappear": "/ˌdɪsəˈpɪr/",
  "attempt": "/əˈtɛmpt/",
  "make sure": "/ˈmeɪk ˈʃʊr/",
  "worthwhile": "/ˈwɝˈθwaɪl/",
  "download": "/ˈdaʊˌnloʊd/",
  "republic": "/riˈpʌblək/",
  "professional": "/prəˈfɛʃənəl/",
  "archaeologist": "/ˌɑrkiˈɑlədʒɪst/",
  "entrance": "/ˈɛntrəns/",
  "pyramid": "/ˈpɪrəmɪd/",
  "process": "/ˈprɑˌsɛs/",
  "overseas": "/ˈoʊvɚˈsiz/",
  "exit": "/ˈɛɡzɪt/",
  "sheet": "/ˈʃit/",
  "parade": "/pɚˈeɪd/",
  "mirror": "/ˈmɪrɚ/",
  "roof": "/ˈruf/",
  "dragon": "/ˈdræɡən/",
  "forgive": "/fɚˈɡɪv/",
  "digital": "/ˈdɪdʒətəl/",
  "image": "/ˈɪmədʒ/",
  "cave": "/ˈkeɪv/",
  "throughout": "/θruˈaʊt/",
  "quality": "/ˈkwɑləti/",
  "all over the world": "/ˈɔl ˈoʊvɚ ðə ˈwɝld/",
  "tradition": "/trəˈdɪʃən/",
  "further": "/ˈfɝðɚ/",
  "historic": "/hɪˈstɔrɪk/",
  "opinion": "/əˈpɪnjən/",
  "quote": "/ˈkwoʊt/",
  "paraphrase": "/ˈpɛrəˌfreɪz/",
  "comparison": "/kəˈmpɛrəsən/",
  "contrast": "/ˈkɑntræst/",
  "identify": "/aɪˈdɛntəˌfaɪ/",
  "forever": "/fɚˈɛvɚ/",
  "poster": "/ˈpoʊstɚ/",
  "illegal": "/ˌɪˈliɡəl/",
  "illegally": "/ˌɪˈliɡəli/",
  "hunt": "/ˈhʌnt/",
  "hunter": "/ˈhʌntɚ/",
  "immediately": "/ˌɪˈmiˌdiətli/",
  "species": "/ˈspiʃiz/",
  "shark": "/ˈʃɑrk/",
  "fin": "/ˈfɪn/",
  "on earth": "/ˈɑn ˈɝθ/",
  "die out": "/ˈdaɪ ˈaʊt/",
  "alarming": "/əˈlɑrmɪŋ/",
  "alarm": "/əˈlɑrm/",
  "rate": "/ˈreɪt/",
  "rating": "/ˈreɪtɪŋ/",
  "extinct": "/ɪˈkstɪŋkt/",
  "extinction": "/ɪˈkstɪŋkʃən/",
  "mass": "/ˈmæs/",
  "habitat": "/ˈhæbəˌtæt/",
  "aware": "/əˈwɛr/",
  "aware of": "/əˈwɛr ˈʌv/",
  "endanger": "/ɛˈndeɪndʒɚ/",
  "average": "/ˈævɚɪdʒ/",
  "on average": "/ˈɑn ˈævɚɪdʒ/",
  "prince": "/ˈprɪns/",
  "make progress": "/ˈmeɪk ˈprɑˌɡrɛs/",
  "concern": "/kəˈnsɝn/",
  "concerned": "/kəˈnsɝnd/",
  "concerned about": "/kəˈnsɝnd əˈbaʊt/",
  "living": "/ˈlɪvɪŋ/",
  "adapt": "/əˈdæpt/",
  "adapt to": "/əˈdæpt ˈtu/",
  "measure": "/ˈmɛʒɚ/",
  "authority": "/əˈθɔrəti/",
  "pressure": "/ˈprɛʃɚ/",
  "under pressure": "/ˈʌndɚ ˈprɛʃɚ/",
  "whale": "/ˈweɪl/",
  "antelope": "/ˈæntəˌloʊp/",
  "tibetan antelope": "/tɪˈbɛtən ˈæntəˌloʊp/",
  "reserve": "/rɪˈzɝv/",
  "plain": "/ˈpleɪn/",
  "make out": "/ˈmeɪk ˈaʊt/",
  "herd": "/ˈhɝd/",
  "observe": "/əˈbzɝv/",
  "beauty": "/ˈbjuti/",
  "remind": "/riˈmaɪnd/",
  "remind sb of sb/sth": "/riˈmaɪnd ˈʌv/",
  "fur": "/ˈfɝ/",
  "sacred": "/ˈseɪkrəd/",
  "shoot": "/ˈʃut/",
  "profit": "/ˈprɑfət/",
  "watch over": "/ˈwɑtʃ ˈoʊvɚ/",
  "day and night": "/ˈdeɪ ənd ˈnaɪt/",
  "attack": "/əˈtæk/",
  "effective": "/ɪˈfɛktɪv/",
  "recover": "/rɪˈkʌvɚ/",
  "remove": "/riˈmuv/",
  "intend": "/ˌɪˈntɛnd/",
  "threat": "/ˈθrɛt/",
  "threaten": "/ˈθrɛtən/",
  "exist": "/ɪˈɡzɪst/",
  "harmony": "/ˈhɑrməni/",
  "goods": "/ˈɡʊdz/",
  "creature": "/ˈkritʃɚ/",
  "deer": "/ˈdɪr/",
  "kangaroo": "/ˌkæŋɡɚˈu/",
  "reduce": "/rəˈdus/",
  "due": "/ˈdu/",
  "due to": "/ˈdu ˈtu/",
  "insect": "/ˈɪˌnsɛkt/",
  "net": "/ˈnɛt/",
  "neighbourhood": "/ˈneɪbɚˌhʊd/",
  "binoculars": "/bəˈnɑkjəlɚz/",
  "bird field guide": "/ˈbɝd ˈfild ˈɡaɪd/",
  "search for": "/ˈsɝtʃ ˈfɔr/",
  "dolphin": "/ˈdɑlfən/",
  "koala": "/koʊˈɑlə/",
  "stir": "/ˈstɝ/",
  "stir up": "/ˈstɝ ˈʌp/",
  "emotion": "/ɪˈmoʊʃən/",
  "skin": "/ˈskɪn/",
  "unusual": "/əˈnjuˌʒuəl/",
  "blog": "/ˈblɔɡ/",
  "blog post": "/ˈblɔɡ ˈpoʊst/",
  "blogger": "/ˈblɔɡɚ/",
  "engine": "/ˈɛndʒən/",
  "search engine": "/ˈsɝtʃ ˈɛndʒən/",
  "chat": "/ˈtʃæt/",
  "stream": "/ˈstrim/",
  "identity": "/aɪˈdɛntɪˌti/",
  "identity card": "/aɪˈdɛntɪˌti ˈkɑrd/",
  "convenient": "/kəˈnvinjənt/",
  "cash": "/ˈkæʃ/",
  "update": "/əˈpdeɪt/",
  "database": "/ˈdeɪtəˌbeɪs/",
  "software": "/ˈsɔˌftwɛr/",
  "network": "/ˈnɛˌtwɝk/",
  "stuck": "/ˈstʌk/",
  "keep sb company": "/ˈkip ˈkʌmpəˌni/",
  "surf": "/ˈsɝf/",
  "benefit": "/ˈbɛnəfɪt/",
  "distance": "/ˈdɪstəns/",
  "inspire": "/ˌɪˈnspaɪr/",
  "now that": "/ˈnaʊ ˈðæt/",
  "access": "/ˈæˌksɛs/",
  "charity": "/ˈtʃɛrɪti/",
  "go through": "/ˈɡoʊ ˈθru/",
  "tough": "/ˈtʌf/",
  "province": "/ˈprɑvəns/",
  "conference": "/ˈkɑnfɚəns/",
  "resident": "/ˈrɛzɪdənt/",
  "plus": "/ˈplʌs/",
  "function": "/ˈfʌŋkʃən/",
  "battery": "/ˈbætɚi/",
  "confirm": "/kəˈnfɝm/",
  "press": "/ˈprɛs/",
  "button": "/ˈbʌtən/",
  "file": "/ˈfaɪl/",
  "in shape": "/ɪn ˈʃeɪp/",
  "keep track of": "/ˈkip ˈtræk ˈʌv/",
  "discount": "/dɪˈskaʊnt/",
  "account": "/əˈkaʊnt/",
  "click": "/ˈklɪk/",
  "privacy": "/ˈpraɪvəsi/",
  "theft": "/ˈθɛft/",
  "rude": "/ˈrud/",
  "target": "/ˈtɑrɡət/",
  "troll": "/ˈtroʊl/",
  "false": "/ˈfɔls/",
  "particular": "/pɚˈtɪkjəlɚ/",
  "embarrassing": "/ɪˈmbɛrəsɪŋ/",
  "make fun of": "/ˈmeɪk ˈfʌn ˈʌv/",
  "upset": "/əˈpsɛt/",
  "guideline": "/ˈɡaɪˌdlaɪn/",
  "author": "/ˈɔθɚ/",
  "tip": "/ˈtɪp/",
  "familiar": "/fəˈmɪljɚ/",
  "keep (...) in mind": "/ˈkip ɪn ˈmaɪnd/",
  "define": "/dɪˈfaɪn/",
  "case": "/ˈkeɪs/",
  "mansion": "/ˈmænʃən/",
  "cemetery": "/ˈsɛməˌtɛri/",
  "philosophy": "/fəˈlɑsəfi/",
  "descendant": "/dɪˈsɛndənt/",
  "individual": "/ˌɪndəˈvɪdʒəwəl/",
  "heel": "/ˈhil/",
  "kingdom": "/ˈkɪŋdəm/",
  "chief": "/ˈtʃif/",
  "puzzle": "/ˈpʌzəl/",
  "nearby": "/ˈnɪˈrbaɪ/",
  "join ... to ...": "/ˈdʒɔɪn ˈtu/",
  "break away (from sb/sth)": "/ˈbreɪk əˈweɪ ˈfrʌm/",
  "belong": "/bɪˈlɔŋ/",
  "belong to": "/bɪˈlɔŋ ˈtu/",
  "as well as": "/ˈæz ˈwɛl ˈæz/",
  "currency": "/ˈkɝənsi/",
  "military": "/ˈmɪləˌtɛri/",
  "defence": "/dɪˈfɛns/",
  "legal": "/ˈliɡəl/",
  "surround": "/sɚˈaʊnd/",
  "evidence": "/ˈɛvədəns/",
  "achievement": "/əˈtʃivmənt/",
  "location": "/loʊˈkeɪʃən/",
  "conquer": "/ˈkɑŋkɚ/",
  "battle": "/ˈbætəl/",
  "port": "/ˈpɔrt/",
  "fascinating": "/ˈfæsəˌneɪtɪŋ/",
  "keep your eyes open (for)": "/ˈkip ˈjɔr ˈaɪz ˈoʊpən ˈfɔr/",
  "charge": "/ˈtʃɑrdʒ/",
  "announce": "/əˈnaʊns/",
  "amount": "/əˈmaʊnt/",
  "gallery": "/ˈɡælɚi/",
  "approach": "/əˈproʊtʃ/",
  "ensure": "/ɛˈnʃʊr/",
  "landscape": "/ˈlæˌndskeɪp/",
  "generous": "/ˈdʒɛnɚəs/",
  "butter": "/ˈbʌtɚ/",
  "honey": "/ˈhʌni/",
  "ancestor": "/ˈæˌnsɛstɚ/",
  "position": "/pəˈzɪʃən/",
  "courtyard": "/ˈkɔˌrtjɑrd/",
  "snack": "/ˈsnæk/",
  "eager": "/ˈiɡɚ/",
  "poet": "/ˈpoʊət/",
  "county": "/ˈkaʊnti/",
  "feast": "/ˈfist/",
  "roll": "/ˈroʊl/",
  "dot": "/ˈdɑt/",
  "cattle": "/ˈkætəl/",
  "roar": "/ˈrɔr/",
  "ocean": "/ˈoʊʃən/",
  "scent": "/ˈsɛnt/",
  "greet": "/ˈɡrit/",
  "pub": "/ˈpʌb/",
  "wine": "/ˈwaɪn/",
  "beer": "/ˈbɪr/",
  "stew": "/ˈstu/",
  "custom": "/ˈkʌstəm/",
  "sensory": "/ˈsɛnsɚi/",
  "striking": "/ˈstraɪkɪŋ/",
  "transition": "/træˈnzɪʃən/",
  "crowd": "/ˈkraʊd/",
  "classical": "/ˈklæsɪkəl/",
  "hip-hop": "/ˈhɪp ˈhɑp/",
  "techno": "/ˈtɛknoʊ/",
  "energy": "/ˈɛnɚdʒi/",
  "soul": "/ˈsoʊl/",
  "bagpipes": "/ˈbæˌɡpaɪps/",
  "stringed": "/ˈstrɪŋd/",
  "stringed instrument": "/ˈstrɪŋd ˈɪnstrəmənt/",
  "virtual": "/ˈvɝtʃuəl/",
  "virtual choir": "/ˈvɝtʃuəl ˈkwaɪɚ/",
  "composition": "/ˌkɑmpəˈzɪʃən/",
  "opportunity": "/ˌɑpɚˈtunəti/",
  "perform": "/pɚˈfɔrm/",
  "performance": "/pɚˈfɔrməns/",
  "performer": "/pɚˈfɔrmɚ/",
  "onto": "/ˈɑntu/",
  "studio": "/ˈstudiˌoʊ/",
  "ordinary": "/ˈɔrdəˌnɛri/",
  "enable": "/ɛˈneɪbəl/",
  "prove": "/ˈpruv/",
  "award": "/əˈwɔrd/",
  "composer": "/kəˈmpoʊzɚ/",
  "conductor": "/kəˈndʌktɚ/",
  "fall in love with": "/ˈfɔl ɪn ˈlʌv ˈwɪð/",
  "original": "/ɚˈɪdʒənəl/",
  "phenomenon": "/fəˈnɑməˌnɑn/",
  "stage": "/ˈsteɪdʒ/",
  "altogether": "/ˌɔltəˈɡɛðɚ/",
  "thus": "/ˈðʌs/",
  "band": "/ˈbænd/",
  "rap": "/ˈræp/",
  "nowadays": "/ˈnaʊəˌdeɪz/",
  "gradual": "/ˈɡrædʒuəl/",
  "capable": "/ˈkeɪpəbəl/",
  "relief": "/rɪˈlif/",
  "cure": "/ˈkjʊr/",
  "absorbed in sb/sth": "/əˈbzɔrbd ɪn/",
  "previous": "/ˈpriviəs/",
  "unemployed": "/ˌʌnɛˈmplɔɪd/",
  "romantic": "/roʊˈmæntɪk/",
  "album": "/ˈælbəm/",
  "impact": "/ˌɪˈmpækt/",
  "aim": "/ˈeɪm/",
  "set sth up": "/ˈsɛt ˈʌp/",
  "equipment": "/ɪˈkwɪpmənt/",
  "try out": "/ˈtraɪ ˈaʊt/",
  "talent": "/ˈtælənt/",
  "piano": "/piˈænoʊ/",
  "assume": "/əˈsum/",
  "addition": "/əˈdɪʃən/",
  "in addition (to sb/sth)": "/ɪn əˈdɪʃən ˈtu/",
  "disease": "/dɪˈziz/",
  "ache": "/ˈeɪk/",
  "treatment": "/ˈtritmənt/",
  "from (then) on": "/ˈfrʌm ˈðɛn ˈɑn/",
  "lean": "/ˈlin/",
  "get through": "/ˈɡɛt ˈθru/",
  "moreover": "/mɔˈroʊvɚ/",
  "satisfaction": "/ˌsætəˈsfækʃən/",
  "being": "/ˈbiɪŋ/",
  "various": "/ˈvɛriəs/",
  "somehow": "/ˈsʌˌmhaʊ/",
  "rhetorical": "/rɪˈtɔrɪkəl/",
  "metaphor": "/ˈmɛtəfɔr/",
  "personification": "/pɚˌsɑnəfəˈkeɪʃən/",
  "repetition": "/ˌrɛpəˈtɪʃən/",
  "outline": "/ˈaʊˌtlaɪn/",
  "reaction": "/riˈækʃən/"
};
